### ISSUE TITLE
tiny suggestion

### ISSUE THREAD

**Issue by fly2mato** [HKUST-Aerial-Robotics/plan_utils#1]
i suggest deleting the two space char just between _\<name\>_ , _rviz_plugins_ and _\<\/name\>_ in _src/plan_utils/rviz_plugins/package.xml_

when i use the origin file and run rviz, an error turns out:
[ERROR] Skipped loading plugin with error: XML Document 'rviz_plugins  /home/catkin_ws/src/plan_utils/rviz_plugins/plugin_description.xml' has no Root Element. This likely means the XML is malformed or missing..

i run this in ubuntu18.04+melodic

**Comment by USTfgaoaa** [comment]
@fly2mato  Ack with thanks. I will correct this immediately.
