### ISSUE TITLE
Can't find SwarmCommand.h

### ISSUE THREAD

**Issue by stevechan1993** [HKUST-Aerial-Robotics/plan_utils#2]
Thank you for your great work.And when I try to build this package in catkin_ws I got an error shows that can't find the file named SwarmCommand.h.

**Comment by ZbyLGsc** [comment]
Thanks for your attention. Some days before I mistakenly add an UAV simulator into the code and it causes the compilation problem. Now the problem should have been solved. You can try it again. :)

**Comment by ZbyLGsc** [comment]
> Thank you for your great work.And when I try to build this package in catkin_ws I got an error shows that can't find the file named SwarmCommand.h.

Thanks for your attention. Some days before I mistakenly add an UAV simulator into the code and it causes the compilation problem. Now the problem should have been solved. You can try it again. :)

**Comment by stevechan1993** [comment]
Thank you very much.It worked!
